### ISSUE TITLE
Game crashes when I place down holders

### ISSUE THREAD

**Issue by Trustybtw** [Minecraft-LightLand/ModularGolems#13]
I downloaded the mod and was excited to use it, but when I try to place any of the holders (golem, humanoids, and dogs), it crashes my game. I have L2Library downloaded and don't use Optifine as well so I don't know what the issue is. If you could fix the issue that would be great.

This is the message that pops up when my game crashes:

The game crashed whilst exception in server tick loop
Error: java.lang.IllegalAccessError: class dev.xkmc.modulargolems.content.entity.common.AbstractGolemEntity tried to access private field net.minecraft.world.entity.Entity.f_19793_ (dev.xkmc.modulargolems.content.entity.common.AbstractGolemEntity is in module modulargolems@2.4.2 of loader 'TRANSFORMER' @40ce9049; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @40ce9049)

**Comment by lcy0x1** [comment]
Could you provide your game version, forge version, mod version, and mod list? This seems to be an Access Transformer Conflict.

**Comment by lcy0x1** [comment]
I see, it's 1.20.1/2.4.2. Let me see what happened

**Comment by lcy0x1** [comment]
Seems that forge changes things in 1.20.1-47.0.35. I will fix it asap

**Comment by lcy0x1** [comment]
Fixed in 2.4.4 https://legacy.curseforge.com/minecraft/mc-mods/modulargolems/files/4622203

**Comment by Trustybtw** [comment]
Worked. Thanks 👍👍👍
