### ISSUE TITLE
the return of golem holders crashing game bug.

### ISSUE THREAD

**Issue by WilliamBlaze** [Minecraft-LightLand/ModularGolems#18]
It appears to be Back again in Modular Golems 2.4.6 for 1.20.1

Even though the bug is only happening during first time i place a golem holder down in a new world - it still does it consistently for all three golem types.
Here's my crash log:

https://pastebin.com/AReufFhg

**Comment by lcy0x1** [comment]
It's caused by "boxadactle" mod. Do you know which mod it is?

**Comment by WilliamBlaze** [comment]
not in the slighest because i dont even have anything in my modlist by that file name. i think its part of Forge's current build? either that or minecraft mods are now hiding invisible in the mod folder' o.o

**Comment by lcy0x1** [comment]
What about “coordinatesdisplay”?

**Comment by lcy0x1** [comment]
boxadactle seems to be the name of the author or team

**Comment by WilliamBlaze** [comment]
okay that mod sounds familiar, https://www.curseforge.com/minecraft/mc-mods/coordinates-display 
i'm not sure how this mod is causing a conflict with modular golems in such a way that it causes players to crash the first time they place down/spawn in a metal, humanoid, and wolf type golem(s) in their worlds(and then never again afterword within the same world) but your right! I removed that mod from the mod pack and gave modular golems a go in creative mode in a fresh world - Zero crashes~

**Comment by lcy0x1** [comment]
Golem has an Overlay UI displaying its states. That should be the thing that causes issue. The problem is that it crashes before reaching my code. Weird.
