### ISSUE TITLE
[Suggestion] Have golem summon/retrieve wands be configurable

### ISSUE THREAD

**Issue by MageInBlack** [Minecraft-LightLand/ModularGolems#19]
I really like the golem follower mechanic, however it seems a bit op that I can use summon wand in particular to place golems far away from me. If it wouldn't be so hard could there be a way to configure the summon wand and maybe the retrieval wand? Like adding a radius they act inside of or use a particular item to do their work or be able to turn them on/off in config file?

**Comment by lcy0x1** [comment]
I will add them in config

**Comment by lcy0x1** [comment]
finished. Released in 2.4.9
