### ISSUE TITLE
[1.19.2] v1.9.4 Golem arms have no icon

### ISSUE THREAD

**Issue by MrNovado** [Minecraft-LightLand/ModularGolems#27]
Possible sprite miss-match, all standard golems' arms are missing icons. 
Only standard golems affected, humanoids are intact.

![image](https://github.com/Minecraft-LightLand/ModularGolems/assets/4604289/f41a869b-3997-4749-a094-462aea421cb6)

**Comment by lcy0x1** [comment]
because some other mods changed the golem model, and my mod use the vanilla golem model. The only way to fix this is to remove that mod who changed vanilla golem model

**Comment by lcy0x1** [comment]
Problem identified: Fresh Animations changed vanilla iron golem model. Remove that mod to fix this visual bug

**Comment by MrNovado** [comment]
Yeah, thx, that is exactly the issue.

To those who stumbles on this, removing the entire resource pack (Fresh Animations or whatever changes the `iron_golem` model) is unnecessary.

Just delete all `iron_golem` folders/files from resource pack, thus nullifying the overrides to iron_golem.
