### ISSUE TITLE
crash when adding items to the filter for pickup

### ISSUE THREAD

**Issue by Vadewolf** [Minecraft-LightLand/ModularGolems#28]
[crash-2023-10-22_12.48.06-client.txt](https://github.com/Minecraft-LightLand/ModularGolems/files/13064100/crash-2023-10-22_12.48.06-client.txt)

**Comment by Vadewolf** [comment]
ok so filters in general just dont seem to work it seems

mod version 2.4.19 forgot that bit oopsy

**Comment by lcy0x1** [comment]
will fix ASAP

**Comment by lcy0x1** [comment]
Fixed in 2.4.20
