### ISSUE TITLE
与NEI不兼容导致的客户端崩溃

### ISSUE THREAD

**Issue by M1hono** [Minecraft-LightLand/ModularGolems#30]
[crash-2023-11-04_18.28.34-client.txt](https://github.com/Minecraft-LightLand/ModularGolems/files/13256369/crash-2023-11-04_18.28.34-client.txt)

**Comment by lcy0x1** [comment]
这是和REI不兼容。原因是我写了JEI兼容，然后REI试图兼容我的JEI兼容，但是出现了找不到JEI代码的问题。
我试试看把JEI的部分代码复制进来能不能解决问题。能加QQ群689206723测试讨论吗？

**Comment by lcy0x1** [comment]
2.4.22修复
