### ISSUE TITLE
more filter slots for golems pls

### ISSUE THREAD

**Issue by Vadewolf** [Minecraft-LightLand/ModularGolems#32]
as the title says id like to know if its possible tp add more filters to the golems cause setting them up for a mob grinder and not having them pick up anything would be so helpful (well not pick up anything except mending ofc)

**Comment by lcy0x1** [comment]
If you set it to whitelist and have no items, then nothing is in whitelist and it picks up nothing. also, it can put items into chest it stands on if you allow it to pick up item.

**Comment by Vadewolf** [comment]
wait how do u tell it to dump items into a chest?
