### ISSUE TITLE
how do u tell golems to put items in chests? 

### ISSUE THREAD

**Issue by Vadewolf** [Minecraft-LightLand/ModularGolems#33]
https://github.com/Minecraft-LightLand/ModularGolems/issues/32

as stated here golems can use chests but how do u tell them to input items to chests?

**Comment by lcy0x1** [comment]
As stated in my patchouli book, when golem attempts to pick up an item, it will:
Check if it has dimensional backpack from L2Backpack. If yes, it puts items into that backpack.
Check if its in standing mode and there is a chest within 2 blocks. If yes, it puts items into that chest.
Check if its owner is alive. If yes, teleport item to owner.
Destroy the item if none of the above mets.

Also, you can re-open the issue, or continue discussion in a closed issue. You don't need to create a new one.

**Comment by Vadewolf** [comment]
ok odd then cause ive had golems always teleport items to me instead of the chest which is closer so

**Comment by lcy0x1** [comment]
The chest could be too far, or the golem might not be in standing mode.

**Comment by Vadewolf** [comment]
its in standing mode and the chest is elgit within 2 blocks of the golem but i wonder if its cause its a modded chest and not vanilla

**Comment by lcy0x1** [comment]
Correct. If you want to use modded chest, please add them to `modulargolems:potential_destination` block tag, so that golems know they are chests.

**Comment by lcy0x1** [comment]
By default, I support `#forge:chests` and `#forge:barrels`. Could be that the chest you are using did not comply with forge tagging standard

**Comment by Vadewolf** [comment]
actually its cause another mod used the forge:chest tag wrongly and it allowed for a 3rd mod (the one im using now) to basically world gen chests that shouldnt of been allowed so i will have to see if i can add them manually unless u can by chance 

https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage

the chest mod im using just to clarify
