### ISSUE TITLE
Golems not targeting players

### ISSUE THREAD

**Issue by Pb414** [Minecraft-LightLand/ModularGolems#34]
I used the command wand to command them to attack a player and they didn’t, any other mob worked.

**Comment by lcy0x1** [comment]
In 1.20.1, golems have config cards. You can edit their hostile/friendly list. The default friendly list includes all players and all golems. If you want them to attack other player, you need to remove the default friendly list and set your own friendly list.

**Comment by Pb414** [comment]
> In 1.20.1, golems have config cards. You can edit their hostile/friendly list. The default friendly list includes all players and all golems. If you want them to attack other player, you need to remove the default friendly list and set your own friendly list.

Whenever I use the config cards on the golem it’s stuck on loading is this normal?

**Comment by lcy0x1** [comment]
That's an issue that I thought I have already fixed. It's just a display issue
