### ISSUE TITLE
导致无法跳劈造成暴击

### ISSUE THREAD

**Issue by Fiocher** [Minecraft-LightLand/ModularGolems#35]
游戏版本：1.20.1
模组版本：2.4.25
使用全新的游戏进行测试，只添加了傀儡装配及其前置，排除了其他模组或数据包的影响。

更正：使用伤害显示模组再次测试，暴击其实是存在的，只是暴击产生的粒子和音效没了。

**Comment by lcy0x1** [comment]
我让暴击允许和横扫同时发生，导致了这个显示问题。我会试看看解决这个问题

**Comment by lcy0x1** [comment]
建议加入QQ：689206723 或者 Discord: https://discord.gg/BCHNhsDMXz 深入讨论

**Comment by lcy0x1** [comment]
Fixed in b8edf572afdd05d61bcb017fe7374c804c0ef39a
