### ISSUE TITLE
1.20.1服务器出现崩溃

### ISSUE THREAD

**Issue by nenglizuida** [Minecraft-LightLand/ModularGolems#36]
[(傀儡装配)crash-2024-01-04_12.45.01-server.txt](https://github.com/Minecraft-LightLand/ModularGolems/files/13826876/crash-2024-01-04_12.45.01-server.txt)

服务器运行过程中崩溃了一次 这是错误日志

**Comment by lcy0x1** [comment]
目前错误报告看不到我的代码。这个是watchdog终止进程，可能造成问题的原因很多，建议加入QQ：689206723 或者 Discord: https://discord.gg/BCHNhsDMXz 深入讨论
