### ISSUE TITLE
incompatibility with HMaG/Befriend Mobs. Days with monster girls.

### ISSUE THREAD

**Issue by Nathanos2256** [Minecraft-LightLand/ModularGolems#37]

**Comment by Nathanos2256** [comment]
the girls will attack the golems without reason its not because they are hostile towards the girls it just seems like the golems agro them. it doesnt happen with normal golems that are not hostile like yours or golems that are hostile towards them until they attack. if you could maybe fix that it would be great!

**Comment by lcy0x1** [comment]
I made mobs that are hostile to golems also hostile to my golem. Which version are you on? I can add a config option for this

**Comment by Nathanos2256** [comment]
1.19.2 is my version

**Comment by Nathanos2256** [comment]
also forge

**Comment by lcy0x1** [comment]
Uploaded
