### ISSUE TITLE
[1.20.1] L2 and Modular creating memory leak on a server (I think).

### ISSUE THREAD

**Issue by InkTheGod** [Minecraft-LightLand/ModularGolems#38]
I made a modded server recently, using a decent number of mods. I wanted to add Modular golems to the server as it was a fantastic golem mod for controlling them and such. However, when we play it keeps spewing out an error along the lines of "Cyclical damage detected" from L2 and after about a half hour to an hour of playing it crashes, somehow running out of memory. The server runs fine without the mod, but I really wanted to get it working, it's a great mod. Would you know why this might be happening?
I can provide the specific reports on the errors or the other mods on the server if you need it.

**Comment by lcy0x1** [comment]
let's talk in discord

**Comment by InkTheGod** [comment]
alright. My discord is 
the_inkless

**Comment by lcy0x1** [comment]
friend request sent. You can also join my discord
