### ISSUE TITLE
1.20.x Recent Cataclysm Update Crashing Modular Golems

### ISSUE THREAD

**Issue by Hexdrix** [Minecraft-LightLand/ModularGolems#42]
4/28 L_Ender's Cataclysm update has broken modular golems compatabililty, causing a crash on startup 
![image](https://github.com/Minecraft-LightLand/ModularGolems/assets/106404475/dddc313b-3e3e-4203-91dc-f663fee30220)

**Comment by lcy0x1** [comment]
fixing. Dev release available in discord

**Comment by lcy0x1** [comment]
uploaded to CurseForge
