### ISSUE TITLE
Skulk Golem parts not created with Echo Shards

### ISSUE THREAD

**Issue by EldonSamuelson** [Minecraft-LightLand/ModularGolems#60]
**Version**: 2.4.37 (_in FTB's Direwolf20, v1.16.0_)

**Issue**:

- Cannot create Skulk Golem Parts (Arms, Legs, Body) with the supplied Recipe and Materials.
    - The recipe will go _through_ the Anvil, but it will not produce Skulk Golem Parts, just a Part without the proper attributes or texture.
        - The Enchantment Cost should be 6, but it is always 1 instead
        - The 9 Echo Shards are used in the process but does not create the correctly attributed Skulk Golem Parts
        - The Output Golem Part will take a Bold Font Name, like it has been renamed in the Anvil, but no expected changes occur to create the Golem Part
    - Recipes for other Golem Parts with other materials (Minecraft Vanilla like Copper and Mods like Manasteel) will work fine and produce expected material Golem Parts.

The issue is illustrated below

_The JEI Recipe for the Skulk Golem Arm_
![JEI Recipe](https://github.com/user-attachments/assets/d4493249-16ed-4490-886b-f5f019fbeae3)

_Applying said Recipe into the Anvil with the Echo Shards as directed_
![Recipe applied to Anvil](https://github.com/user-attachments/assets/8b39a240-6df0-4dcf-801b-34673cc3b261)

_Unexpected Output: Not a Skulk Golem Arm, but a renamed standard Metal Golem Arm_
![Anvil Output is NOT Skulk](https://github.com/user-attachments/assets/b938e34f-e64e-4db6-b259-8a77f6fcb297)

_The illustrated error has a slightly incorrect recipe as only one Echo Shard is entered, but in other attempts with using 9 Echo Shards, the same result is as above. It is interesting that the recipe can go through at all without the correct number of materials, so that may be another bug in the process._

This issue occurred with the mod in conjunction with using FTB Direwolf20's Modpack. I am uncertain if the pack has significantly altered the recipes or inadvertently created a bug, but I will also report it to the FTB Team as well.

**Comment by lcy0x1** [comment]
Looks like some other mod mechanics are intervene, for example, use echo shard to make name bold. I'm in Direwolf's discord as well. Ping me there

**Comment by lcy0x1** [comment]
timeout. Contact me if you want further discussion

**Comment by andreash-dev** [comment]
I have the same issue and i can't figure out what mod that interfere with it. Any clues? 
Modpack: Direwolf20 1.20.1

**Comment by lcy0x1** [comment]
It should be some mod with the feature of using vanilla special ingredients to apply special text effect to item name, and echo shard happened to be the material for bold effect

**Comment by andreash-dev** [comment]
I give an update if I find the mod.
